### ISSUE TITLE
Background features

### ISSUE THREAD

**Issue by tsumo** [tsumo/space-shooter-godot#1]
# Make backgrounds more interesting and beautiful

## Phase 1
* [x] Static scrolling picture

## Phase 2
* [x] Background tone layer
* [x] Stars layer
* [x] Planets layer
* [ ] Low floating debris (under player)
* Player
* [ ] High floating debris (above player)

## Phase 3
* [ ] Destructible background objects
