### ISSUE TITLE
Enemy movement features

### ISSUE THREAD

**Issue by tsumo** [tsumo/space-shooter-godot#2]
# Make enemy movement patterns more interesting

## Phase 1
* [ ] Simple hardcoded movement pattern

## Phase 2
* [ ] Trigonomerty functions-based movement patterns

## Phase 3
* [ ] Spline-based movement patterns
