### ISSUE TITLE
Player features

### ISSUE THREAD

**Issue by tsumo** [tsumo/space-shooter-godot#4]
# Make player-controlled sprite prettier

## Phase 1
* [x] Simple ship sprite
* [x] Simple animated flame sprite

## Phase 2
* [ ] Better sprites
* [x] Separate sprites for player ship tilting while stafing
